### ISSUE TITLE
Problem using compressed N5

### ISSUE THREAD

**Issue by ericvaughn11** [PreibischLab/RS-FISH#25]
Hi and thanks for the excellent work on this package. I can run RS-FISH on an uncompressed N5 just fine. However, when trying to run the same on a compressed zarr N5, I'm immediately hitting this snag:

```
java.lang.NullPointerException
        at org.janelia.saalfeldlab.n5.CompressionAdapter.deserialize(CompressionAdapter.java:146)
        at org.janelia.saalfeldlab.n5.CompressionAdapter.deserialize(CompressionAdapter.java:57)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at org.janelia.saalfeldlab.n5.GsonAttributesParser.parseAttribute(GsonAttributesParser.java:78)
        at org.janelia.saalfeldlab.n5.AbstractGsonReader.getDatasetAttributes(AbstractGsonReader.java:95)
        at net.preibisch.rsfish.spark.SparkRSFISH.call(SparkRSFISH.java:131)
        at net.preibisch.rsfish.spark.SparkRSFISH.call(SparkRSFISH.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at net.preibisch.rsfish.spark.SparkRSFISH.main(SparkRSFISH.java:338)
```

I looked into https://github.com/saalfeldlab/n5-blosc and installed this, along with the necessary https://github.com/Blosc/c-blosc, but am still seeing this issue.

Btw, I realize this is not in the RS-FISH-Spark repository but this repository seems to be more active.

Thanks,
Eric

**Comment by LauraBreimann** [comment]
Hi Eric, thanks for the note! 

@mzouink could you have a look at this?

**Comment by mzouink** [comment]
Hi @ericvaughn11  

Can you please help me with this informations:
- What is the used OS and the CPU ? 
- Did you got Blosc related bugs or warnings in the console? 
- Did you got the bug within the Spark version or the desktop version ?

My preliminary assumption is either because of blosc jni or spark serialization
